### ISSUE TITLE
Does not work with jQuery 3.1.1

### ISSUE THREAD

**Issue by hth** [mrmarkfrench/country-select-js#37]
Drop down is missing flags and countries when using `jQuery 3.1.1`

Error: 

        jquery.min.js:4 Uncaught TypeError: a.indexOf is not a function
	r.fn.load @ jquery.min.js:4
	(anonymous function) @ countrySelect.min.js:1
	(anonymous function) @ countrySelect.min.js:1
	(anonymous function) @ countrySelect.min.js:1
	..... Uncaught TypeError: $(...).countrySelect is not a function(anonymous function) @

**Comment by hth** [comment]
Pull https://github.com/mrmarkfrench/country-select-js/pull/34 fixes this issue.
